// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1234.SathiraRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc1234.SathiraRobot.commands.DriveStraight;
import org.usfirst.frc1234.SathiraRobot.Robot;

/**
 *
 */
public class  AutonomousCommand extends CommandGroup {

    public AutonomousCommand(){
    	addSequential(new PrepareToPickup());
    	addSequential(new Pickup());
    	addSequential(new SetDistanceToBox(0.1));
    	addSequential(new Place());
    	addSequential(new SetDistanceToBox(0.55));
    	addParallel(new SetWristSetPoint(-50));
    	addParallel(new CloseClaw());
    	
    	addSequential(new PrepareToPickup());
    	addSequential(new Turn(175));
    	addSequential(new Turn(48));
    	addSequential(new DriveStraight(-1.4));
    	addSequential(new DriveStraight(1));
    	addSequential(new Pickup());
    }
}
