// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1234.SathiraRobot.subsystems;

import org.usfirst.frc1234.SathiraRobot.RobotMap;
import org.usfirst.frc1234.SathiraRobot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;

public class Claw extends Subsystem {
    SpeedController motor = RobotMap.clawMotor;
    private DigitalInput clawContact;

    public void initDefaultCommand() {
      
    }
    
    public Claw(){
    	super();
    	clawContact = new DigitalInput(5);
    }
    
    public void open(){
    	motor.set(-1);
    }
    
    public void close(){
    	motor.set(1);
    }
    
    public void stop(){
    	motor.set(0);
    }
    public boolean isGrabbing(){
    	return clawContact.get();
    }
}

